### PR TITLE
Unicode icons for playing status

### PR DESCRIPTION
**Pull request by istathar**
This may be a bridge too far, but there are Unicode symbols for Play, Pause, and Stop: `⏵`, `⏸`, and `⏹`. I dug them up, and threw them in to see how they'd look rather than the `||` and `|>` hacks. Seems ok running locally here :)

Sourced, eventually, from <http://www.fileformat.info/info/unicode/block/miscellaneous_technical/list.htm>

### CODE REVIEW

**Comment by RichiH** [comment]
This breaks the tests. Also, BLACK MEDIUM RIGHT-POINTING TRIANGLE (U+23F5) is shown left-facing consistently on Linux & Chrome.

I suspect this would need run-time detection if the tty speaks UTF8.

**Comment by RichiH** [comment]
https://travis-ci.org/vimus/vimus/jobs/223912891#L802 - 9205 is 0x23F5, i.e. the play symbol.

**Comment by joachifm** [comment]
Very cool :) I'd prefer it be configurable at run or compile time, however, so I probably won't merge this as is (but I'd leave it open indefinetely so people can find it more easily).

**Comment by RichiH** [comment]
FTR, I submitted a bug to the Symbola font regarding the way the triangle points. fonts-symbola 2.59-1 on Debian is affected at least.

**Comment by afcowie** [comment]
@joachifm that's quite ok. I just wanted to try it, and having done so wanted to show you.

**Pull request closed without merging**
