### PR TITLE
Mention command-line opts and env vars in README

### PR DESCRIPTION
**Pull request by sid-kap**
Follow-up to #79. 

Does this look okay, or would you prefer a few sentences about these options instead?

### CODE REVIEW

**Comment by joachifm** [comment]
I prefer a brief section that describes how to configure the connection to MPD.

**Comment by sid-kap** [comment]
Does this look better?

**Comment by joachifm** [comment]
Looks good to me. Please squash the commits.

**Comment by sid-kap** [comment]
Done!

**Comment by joachifm** [comment]
Thanks!

**Pull request merged**
